language: ruby
rvm:
  - 2.1.1
addons:
  postgresql: "9.3"
env:
  - DB=postgresql
script:
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rspec
before_script:
  - psql -c 'create database bolao_test;' -U postgres
