language: ruby
rvm:
- 2.1.1
addons:
  postgresql: '9.3'
env:
  matrix:
  - DB=postgresql
  global:
    secure: NXzl/FbZC/gBuoXfrtDfLn8NYIjFYoegSbRncyX2rEd4rmPy5vn7vBoG/k6zdYvYc4uKBfiLcwHIVLJAJa/JYut3sfxtysQUawsz3GH2HiINtecQ9w2v1PA2B8+Dm2d9zX3VNIQZEe8EzZ+JTnkZvdMT7+kuEX9FUo+NXjXJtmQ=
script:
- bundle exec rake db:migrate RAILS_ENV=test
- bundle exec rspec
before_script:
- psql -c 'create database bolao_test;' -U postgres
